### ISSUE TITLE
How do we actually move our minted nft

### ISSUE THREAD

**Issue by larsen1921** [NodleCode/docs.nodle.com#114]
How do we actually move our minted nft.....I can't seem 2 do it

**Comment by spacesmutje** [comment]
It's as easy as you would normally execute a transaction within the Nodle Cash app. Select the NFT from your wallet, click on transfer, select one of your contacts/paste the public key/scan a qr code, press send and wait for the confirmation. 

And you're all set!

**Comment by ETeissonniere** [comment]
Closing as answered.
