### ISSUE TITLE
Allow in-browser storage of accounts

### ISSUE THREAD

**Issue by spacesmutje** [NodleCode/docs.nodle.com#87]
Apparently the polkadot.js extension has deactivated the in-browser storage by default. Inexperienced users have problems to import their account, so we need to add an explainer that guides them through the process:

- go to settings
- set allow in-browser storage

![Screenshot 2023-03-09 13 42 02](https://github.com/NodleCode/docs.nodle.com/assets/106772187/a8ae3326-d4bf-4eb5-91bd-e9d94aad0d7f)

**Comment by ETeissonniere** [comment]
@spacesmutje do you wanna take a stab at it?

**Comment by spacesmutje** [comment]
> @spacesmutje do you wanna take a stab at it?

Sure, why not. Let me fork this 😌
